// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hdMqa6Ahl_XOY_gOHDZqd3werYjC4Gs',
    appId: '1:198178672858:web:5db4b20d74066a0f72d5e3',
    messagingSenderId: '198178672858',
    projectId: 'questionbank-diu',
    authDomain: 'questionbank-diu.firebaseapp.com',
    databaseURL: 'https://questionbank-diu-default-rtdb.firebaseio.com',
    storageBucket: 'questionbank-diu.appspot.com',
    measurementId: 'G-HBTPNC9TCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVtI_JHZsGXU0eGjbG0ELMTl-7bKzHo0',
    appId: '1:198178672858:android:29aa6599c8cb03d372d5e3',
    messagingSenderId: '198178672858',
    projectId: 'questionbank-diu',
    databaseURL: 'https://questionbank-diu-default-rtdb.firebaseio.com',
    storageBucket: 'questionbank-diu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6_wHFHE_U7C0V1f38KzPQ2Zs6rbShes',
    appId: '1:198178672858:ios:d7f6e53cc89646ae72d5e3',
    messagingSenderId: '198178672858',
    projectId: 'questionbank-diu',
    databaseURL: 'https://questionbank-diu-default-rtdb.firebaseio.com',
    storageBucket: 'questionbank-diu.appspot.com',
    androidClientId: '198178672858-1db84brbm9na27njehm3h97k88kjpge6.apps.googleusercontent.com',
    iosClientId: '198178672858-a7fauv8ian37ompgho91higodhti84pa.apps.googleusercontent.com',
    iosBundleId: 'com.fourdevs.diuquestionbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6_wHFHE_U7C0V1f38KzPQ2Zs6rbShes',
    appId: '1:198178672858:ios:cf83a69902e7957c72d5e3',
    messagingSenderId: '198178672858',
    projectId: 'questionbank-diu',
    databaseURL: 'https://questionbank-diu-default-rtdb.firebaseio.com',
    storageBucket: 'questionbank-diu.appspot.com',
    androidClientId:
        '198178672858-1db84brbm9na27njehm3h97k88kjpge6.apps.googleusercontent.com',
    iosClientId:
        '198178672858-95v9po95urlis3g4b2vitr56988tj0u3.apps.googleusercontent.com',
    iosBundleId: 'com.fourdevs.diuQuestionBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9hdMqa6Ahl_XOY_gOHDZqd3werYjC4Gs',
    appId: '1:198178672858:web:dd9de5966c3a47c672d5e3',
    messagingSenderId: '198178672858',
    projectId: 'questionbank-diu',
    authDomain: 'questionbank-diu.firebaseapp.com',
    databaseURL: 'https://questionbank-diu-default-rtdb.firebaseio.com',
    storageBucket: 'questionbank-diu.appspot.com',
    measurementId: 'G-BY08NQW8LE',
  );
}